window.CHAPTERS = [
  {
    "id": "ch01",
    "title": "Why Monitor? The Dashboard You Can't Drive Without",
    "analogy": "Driving a car without a dashboard",
    "emoji": "🚗",
    "desc": "What monitoring really is, RED/USE methods, and why logs alone will fail you at 2AM.",
    "content": "\n<h2>🚗 The Problem: You're Driving Blind</h2>\n<p>Imagine driving at 120km/h at night with no dashboard - no speed, fuel, temperature. That's running servers without monitoring. You'll only know something is wrong when the engine smokes.</p>\n<div class=\"analogy\"><strong>🏠 Power Analogy:</strong> You wouldn't rent an apartment without an electricity meter. How would you know the bill? Monitoring = meter + bill + alert when over budget.</div>\n\n<h3>Logs vs Metrics vs Traces</h3>\n<ul>\n<li><b>Logs:</b> \"At 2:03:14, apartment 4B door opened\" — detailed events (like a diary)</li>\n<li><b>Metrics:</b> \"4B used 12kWh in last 5 min\" — numbers over time (like meter)</li>\n<li><b>Traces:</b> \"Guest went lobby -> elevator -> 4B (2.3s)\" — journey (like security camera tracking)</li>\n</ul>\n<p>Prometheus is best at <b>metrics</b>. That's 80% of what you need to know if your system is healthy.</p>\n\n<h3>RED & USE Methods</h3>\n<pre><code>RED (for services): Rate, Errors, Duration\nUSE (for resources): Utilization, Saturation, Errors\n\nExample: Web API\nRED: 500 req/s, 2% errors, 230ms p95\nUSE: CPU 70%, disk queue 3, network errors 0\n</code></pre>\n\n<div class=\"lab\"><strong>🧪 Lab 1 Preview:</strong> We'll install Prometheus and see <code>up == 1</code> — the universal \"I'm alive\" signal. Think: meter reports \"building has power\".</div>\n\n<h3>Why Prometheus? Not Nagios, not Zabbix?</h3>\n<p>Prometheus pulls (meter reader visits you), stores time-series efficiently, PromQL is powerful calculator, cloud-native, and free. De-facto standard in Kubernetes.</p>\n"
  },
  {
    "id": "ch02",
    "title": "Architecture: The Meter Reader System",
    "analogy": "Apartment building with central meter reader",
    "emoji": "🏗️",
    "desc": "How Prometheus works: pull model, TSDB, scrape targets, architecture components.",
    "content": "\n<h2>🏗️ The Building Blueprint</h2>\n<p>1. Each apartment has a <b>Meter (Exporter)</b> on the wall at <code>/metrics</code><br>\n2. A <b>Meter Reader (Prometheus Server)</b> walks every 15s and copies all meters<br>\n3. He stores them in a huge notebook (TSDB)<br>\n4. You use a <b>Calculator (PromQL)</b> to analyze<br>\n5. If something weird, <b>Trip Switch (Alert Rule)</b> triggers<br>\n6. <b>Security Guard Room (Alertmanager)</b> decides who to wake up</p>\n\n<pre><code>     [Node Exporter :9100/metrics]       [App :8080/metrics]          ---->  Prometheus Server (pulls every 15s) --> TSDB\n     [Blackbox :9115/metrics]      /           |\n                                               |---> PromQL API / UI (9090)\n                                               |---> Alert Rules --> Alertmanager --> Slack/PagerDuty/Email\n</code></pre>\n\n<h3>Pull vs Push - Why Pull is Genius</h3>\n<ul>\n<li>You control frequency, not apps</li>\n<li>One place to see what's down (target down = meter not reachable)</li>\n<li>Easier to reason: <code>up</code> metric tells you scrape success</li>\n<li>Apps don't need to know Prometheus exists, just expose numbers</li>\n</ul>\n\n<h3>Core Components</h3>\n<pre><code>prometheus.yml -> scrape_configs:\n  - job_name: 'node'\n    static_configs:\n      - targets: ['localhost:9100']\n\nData: /prometheus (TSDB blocks, 2h chunks)\nRetention: --storage.tsdb.retention.time=15d\n</code></pre>\n\n<div class=\"analogy\"><strong>Tip:</strong> Exporter does NOT push. Prometheus asks: \"Hey meter at 9100, what do you have?\" That's HTTP GET /metrics</div>\n"
  },
  {
    "id": "ch03",
    "title": "Metrics Types: Reading Your Utility Bill",
    "analogy": "Electricity bill has different types of charges",
    "emoji": "📊",
    "desc": "Counter, Gauge, Histogram, Summary - never confuse again.",
    "content": "\n<h2>📊 4 Types Only</h2>\n<table>\n<tr><th>Type</th><th>Analogy</th><th>Example</th><th>Can go down?</th></tr>\n<tr><td><b>Counter</b></td><td>Odometer / Total kWh ever used</td><td>http_requests_total</td><td>NEVER (only reset to 0)</td></tr>\n<tr><td><b>Gauge</b></td><td>Current temperature / current kW</td><td>node_memory_free_bytes</td><td>Yes, up and down</td></tr>\n<tr><td><b>Histogram</b></td><td>Bill broken into buckets: 0-10,10-50...</td><td>http_duration_seconds</td><td>Buckets are counters</td></tr>\n<tr><td><b>Summary</b></td><td>Pre-calculated average bill sent by meter</td><td>rpc_duration_seconds (with quantiles)</td><td>Similar but client-side quantiles</td></tr>\n</table>\n\n<h3>Counter - The Golden Rule: Always use rate()</h3>\n<pre><code># WRONG - raw counter is useless over time graph goes up forever\nhttp_requests_total\n\n# RIGHT - how many per second in last 5m\nrate(http_requests_total[5m])\n\n# Total in last hour\nincrease(http_requests_total[1h])\n</code></pre>\n\n<h3>Gauge - Direct value</h3>\n<pre><code>node_cpu_seconds_total  # Actually counter!\nnode_memory_MemAvailable_bytes  # Gauge\n# No rate needed\nnode_memory_MemAvailable_bytes / node_memory_MemTotal_bytes * 100\n</code></pre>\n\n<h3>Histogram - How to calculate p95</h3>\n<pre><code># Exposed as 3 metrics:\nhttp_request_duration_seconds_bucket{le=\"0.1\"} 42\nhttp_request_duration_seconds_bucket{le=\"0.5\"} 100\nhttp_request_duration_seconds_bucket{le=\"+Inf\"} 120\nhttp_request_duration_seconds_sum 65.3\nhttp_request_duration_seconds_count 120\n\n# PromQL:\nhistogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m]))\n</code></pre>\n\n<div class=\"lab\"><strong>🧪 Lab 2: Custom Exporter</strong> Build a Python meter that counts visits.</div>\n<pre><code># pip install prometheus_client\nfrom prometheus_client import Counter, start_http_server\nimport time\nc = Counter('myapp_visits_total','Total visits')\nstart_http_server(8000)\nwhile True:\n    c.inc()\n    time.sleep(2)\n</code></pre>\n"
  },
  {
    "id": "ch04",
    "title": "Install & First Scrape",
    "analogy": "Installing your first power meter and reading it",
    "emoji": "🔧",
    "desc": "Install Prometheus, Node Exporter, verify targets, first graph.",
    "content": "\n<h2>🔧 Lab 1: Hello, Prometheus</h2>\n<p>Goal: Two containers talking, you see <code>up == 1</code>.</p>\n\n<h3>Option A: Docker (fastest)</h3>\n<pre><code>cat > prometheus.yml <<'YML'\nglobal:\n  scrape_interval: 15s\nscrape_configs:\n  - job_name: 'prometheus'\n    static_configs:\n      - targets: ['localhost:9090']\n  - job_name: 'node'\n    static_configs:\n      - targets: ['node-exporter:9100']\nYML\n\ndocker network create mon\ndocker run -d --name prometheus --network mon -p 9090:9090 \\\n  -v $(pwd)/prometheus.yml:/etc/prometheus/prometheus.yml prom/prometheus\n\ndocker run -d --name node-exporter --network mon -p 9100:9100 prom/node-exporter\n\n# Open http://localhost:9090 -> Status -> Targets -> Should be GREEN (UP)\n</code></pre>\n\n<h3>Option B: Linux binary</h3>\n<pre><code>wget https://github.com/prometheus/prometheus/releases/download/v2.52.0/prometheus-2.52.0.linux-amd64.tar.gz\ntar xvfz prometheus-*.tar.gz\ncd prometheus-*\n./prometheus --config.file=prometheus.yml --storage.tsdb.path=./data\n</code></pre>\n\n<h3>Your First PromQL</h3>\n<pre><code># Are my meters responding?\nup\n\n# How long Prometheus has been up (gauge)\ntime() - process_start_time_seconds{job=\"prometheus\"}\n\n# CPU not idle\n100 - (avg by(instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)\n</code></pre>\n\n<div class=\"analogy\">🎯 Success = You see two green targets and can graph <code>node_cpu_seconds_total</code>. That's your first building with working meters.</div>\n"
  },
  {
    "id": "ch05",
    "title": "Exporters: Meters for Everything",
    "analogy": "Different meters for water, gas, electricity, parking gate",
    "emoji": "🔌",
    "desc": "Node Exporter, Blackbox, cAdvisor, MySQL, and custom exporters deep dive.",
    "content": "\n<h2>🔌 One Meter Per Concern</h2>\n<p>Prometheus itself only scrapes. Exporters translate world into metrics.</p>\n\n<table>\n<tr><th>Exporter</th><th>What it meters</th><th>Port</th></tr>\n<tr><td>Node Exporter</td><td>Linux host: CPU, mem, disk, network</td><td>9100</td></tr>\n<tr><td>cAdvisor</td><td>Containers</td><td>8080</td></tr>\n<tr><td>Blackbox</td><td>Is website up? Ping/HTTP from outside</td><td>9115</td></tr>\n<tr><td>mysqld_exporter</td><td>MySQL stats</td><td>9104</td></tr>\n<tr><td>postgres_exporter</td><td>Postgres</td><td>9187</td></tr>\n<tr><td>Custom</td><td>Your app business metrics</td><td>You define</td></tr>\n</table>\n\n<h3>Blackbox - Guard Patrol Example</h3>\n<pre><code># blackbox.yml\nmodules:\n  http_2xx:\n    prober: http\n    http:\n      preferred_ip_protocol: ip4\n\n# prometheus.yml\nscrape_configs:\n  - job_name: blackbox-http\n    metrics_path: /probe\n    params:\n      module: [http_2xx]\n    static_configs:\n      - targets: ['https://example.com','https://google.com']\n    relabel_configs:\n      - source_labels: [__address__]\n        target_label: __param_target\n      - source_labels: [__param_target]\n        target_label: instance\n      - target_label: __address__\n        replacement: blackbox-exporter:9115\n\n# Query: Is site up?\nprobe_success == 0  # FAILED\nprobe_duration_seconds\n</code></pre>\n\n<h3>Custom Exporter Pattern (Best Practice)</h3>\n<pre><code># Python robust pattern\nfrom prometheus_client import Gauge, Counter, Histogram, start_http_server\n\nORDER_VALUE = Histogram('shop_order_value_dollars','Order value',buckets=[5,20,100,500])\nORDERS_TOTAL = Counter('shop_orders_total','Orders', ['status'])\nINVENTORY = Gauge('shop_inventory_items','Stock')\n\ndef process_order(value):\n    with ORDER_VALUE.time(): # measures duration too if you want\n        ORDER_VALUE.observe(value)\n        ORDERS_TOTAL.labels(status='success').inc()\n</code></pre>\n\n<div class=\"lab\"><strong>🧪 Lab 8 Preview:</strong> Use blackbox to monitor 5 public sites + your own app. Create dashboard of uptime.</div>\n"
  },
  {
    "id": "ch06",
    "title": "Service Discovery: Auto-Finding Meters",
    "analogy": "New apartments auto-register their meter",
    "emoji": "🧭",
    "desc": "Static vs file_sd vs DNS vs Kubernetes SD, relabeling magic.",
    "content": "\n<h2>🧭 You Can't Manually List 500 Apartments</h2>\n<p>Static config doesn't scale. Service Discovery = building manager gives you live list of apartments.</p>\n\n<h3>File SD - Simple and Powerful</h3>\n<pre><code># prometheus.yml\nscrape_configs:\n  - job_name: 'apps'\n    file_sd_configs:\n      - files: ['/etc/prometheus/targets/*.json']\n        refresh_interval: 30s\n\n# /etc/prometheus/targets/apps.json\n[\n  {\"targets\":[\"app1:8080\",\"app2:8080\"], \"labels\":{\"env\":\"prod\",\"team\":\"checkout\"}},\n  {\"targets\":[\"app3:8080\"], \"labels\":{\"env\":\"staging\"}}\n]\n# Change file, Prometheus auto picks without restart!\n</code></pre>\n\n<h3>Relabeling - The Secret Weapon</h3>\n<p>Relabeling = fix name tags before saving. Like security guard rewriting visitor badge to proper format.</p>\n<pre><code>relabel_configs:\n  # Keep only prod\n  - source_labels: [env]\n    regex: prod\n    action: keep\n  \n  # Drop unhealthy instances\n  - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]\n    action: keep\n    regex: true\n\n  # __address__ -> instance label manipulation\n  - source_labels: [__address__]\n    target_label: instance\n    regex: '([^:]+):.*'\n</code></pre>\n\n<h3>Kubernetes SD</h3>\n<pre><code>scrape_configs:\n  - job_name: 'kubernetes-pods'\n    kubernetes_sd_configs:\n      - role: pod\n    relabel_configs:\n      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]\n        action: keep\n        regex: true\n</code></pre>\n\n<div class=\"lab\"><strong>🧪 Lab 3:</strong> Create file_sd JSON, change it live, watch targets update in UI without restart.</div>\n"
  },
  {
    "id": "ch07",
    "title": "PromQL Fundamentals: The Calculator Basics",
    "analogy": "Calculator for your electricity bills",
    "emoji": "🧮",
    "desc": "Selectors, range vectors, rate, irate, aggregations, labels.",
    "content": "\n<h2>🧮 Your Calculator Manual</h2>\n\n<h3>Selectors</h3>\n<pre><code>http_requests_total  # instant vector - current value\nhttp_requests_total[5m]  # range vector - last 5 min values (needs function)\nhttp_requests_total{status=\"500\", env=\"prod\"}  # filter\nhttp_requests_total{status=~\"5..\"}  # regex match\nhttp_requests_total{env!=\"staging\"}  # not equal\n</code></pre>\n\n<h3>The Must-Know Functions</h3>\n<pre><code># COUNTERS -> always wrap\nrate(http_requests_total[5m])  # per-second average over 5m (smooth)\nirate(http_requests_total[5m])  # instant per-second (spiky, for fast alerts)\nincrease(http_requests_total[1h])  # total growth in 1h\n\n# GAUGES -> direct\nnode_memory_MemAvailable_bytes\navg_over_time(node_memory_MemAvailable_bytes[5m])\n\n# Time\ntime()\ntimestamp(metric)\n</code></pre>\n\n<h3>Aggregation - Summarize buildings</h3>\n<pre><code>sum(rate(http_requests_total[5m]))\nsum by (status) (rate(http_requests_total[5m]))\nsum without (instance) (rate(http_requests_total[5m]))\n\navg, min, max, count, group, bottomk, topk\n\n# Top 5 CPU hogs\ntopk(5, sum by (instance) (rate(node_cpu_seconds_total{mode!=\"idle\"}[5m])))\n</code></pre>\n\n<h3>Arithmetic & Comparison</h3>\n<pre><code># Math\nnode_memory_MemTotal_bytes - node_memory_MemAvailable_bytes\n\n# % memory used\n100 * (1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)\n\n# Comparison returns 0/1 but useful for alerts\nup == 0\nnode_filesystem_free_bytes / node_filesystem_size_bytes * 100 < 10\n</code></pre>\n\n<div class=\"lab\"><strong>🧪 Lab 4:</strong> 25 queries workout: find p95, error rate, disk full prediction, cold instances.</div>\n"
  },
  {
    "id": "ch08",
    "title": "PromQL Advanced: Joins, Subqueries & Predictions",
    "analogy": "Comparing bills from multiple buildings + forecasting",
    "emoji": "📈",
    "desc": "Vector matching, offset, subqueries, predict_linear, absent.",
    "content": "\n<h2>📈 Advanced Calculator Tricks</h2>\n\n<h3>Offset - Compare bills last week</h3>\n<pre><code># Growth vs last week same time\nrate(http_requests_total[5m]) / rate(http_requests_total[5m] offset 1w)\n\n# Was up before?\nup == 0 and up offset 1h == 1  # just went down in last hour\n</code></pre>\n\n<h3>Vector Matching - Join two bills</h3>\n<pre><code># Each request total * latency? Need matching labels\n# one-to-one\nhttp_requests_total * on(instance) group_left(version) app_info\n\n# Common: CPU + memory of same pod\n(sum by (pod) (rate(container_cpu_usage_seconds_total[5m])) )\n  * on(pod) group_left\n(sum by (pod) (container_memory_usage_bytes))\n\n# Ignoring labels\nsum without (cpu) (rate(node_cpu_seconds_total[5m])) \n  / ignoring(cpu) group_left count without (cpu) (node_cpu...)\n</code></pre>\n\n<h3>Predict & Forecast (SRE Superpower)</h3>\n<pre><code># Will disk be full in 4 hours?\npredict_linear(node_filesystem_free_bytes{mountpoint=\"/\"}[1h], 4*3600) < 0\n\n# Will we run out of memory?\npredict_linear(node_memory_MemAvailable_bytes[1h], 3600) < 0\n</code></pre>\n\n<h3>Absent & Missing Data</h3>\n<pre><code># Alert if metric disappears\nabsent(up{job=\"critical-api\"}) == 1\nabsent_over_time(http_requests_total[5m])\n\n# Return if at least one down\ncount(up == 0) > 0\n</code></pre>\n\n<h3>Subqueries - Rate of rate</h3>\n<pre><code># Rate over last 5m, but evaluated over last 30m, every 1m\navg_over_time(rate(http_requests_total[5m])[30m:1m])\n\n# Smoothed max rate in last hour\nmax_over_time(rate(http_requests_total[5m])[1h:1m])\n</code></pre>\n"
  },
  {
    "id": "ch09",
    "title": "Recording Rules: Pre-Calculated Bills",
    "analogy": "Accountant pre-calculates monthly summary so you don't recalc every time",
    "emoji": "🧾",
    "desc": "Why recording rules matter, how to write, SLO examples.",
    "content": "\n<h2>🧾 Why Calculate Same Thing 100 Times?</h2>\n<p>If your dashboard queries <code>sum(rate(http_requests_total[5m])) by (job)</code> 20 times, that's wasteful. Pre-calc it once.</p>\n\n<h3>rules.yml</h3>\n<pre><code>groups:\n  - name: api-slo\n    interval: 30s\n    rules:\n      - record: job:http_requests_total:rate5m\n        expr: sum by (job) (rate(http_requests_total[5m]))\n\n      - record: job:http_requests:errors:rate5m\n        expr: sum by (job) (rate(http_requests_total{status=~\"5..\"}[5m]))\n\n      - record: job:http_requests:error_ratio5m\n        expr: job:http_requests:errors:rate5m / job:http_requests_total:rate5m\n\n      - record: job:http_latency:p95:5m\n        expr: histogram_quantile(0.95, sum by (le,job) (rate(http_request_duration_seconds_bucket[5m])))\n</code></pre>\n\n<h3>prometheus.yml</h3>\n<pre><code>rule_files:\n  - \"rules.yml\"\n\n# Check: Prom UI -> Rules -> should be GREEN\n</code></pre>\n\n<h3>Naming Convention</h3>\n<pre><code>level:metric:operations\njob:latency:p95 etc.\n\nGood: job:http_requests:error_ratio5m\nBad: my_rule_1\n</code></pre>\n\n<h3>SLO Burn Rate Example (Production gold)</h3>\n<pre><code># For 99.9% SLO, burn rate\n- record: job:slo_errors_per_request:ratio_rate5m\n  expr: job:http_requests:error_ratio5m / (1 - 0.999)  # 0.001 allowed\n\n# Alert if burning too fast: 14x burn rate = 5% budget in 1 hour\n- alert: HighErrorBudgetBurn\n  expr: job:slo_errors_per_request:ratio_rate5m > 14\n  for: 5m\n</code></pre>\n\n<div class=\"lab\"><strong>🧪 Lab 5:</strong> Create recording rules, prove dashboard loads 10x faster with pre-calculated metrics.</div>\n"
  },
  {
    "id": "ch10",
    "title": "Alerting Rules: Smart Trip Switches",
    "analogy": "Fuse box that trips only when really dangerous, not every flicker",
    "emoji": "🚨",
    "desc": "How to write alerts that don't spam, for, labels, annotations, anti-patterns.",
    "content": "\n<h2>🚨 The Wrong Alert Wakes You at 3AM for Nothing</h2>\n\n<h3> anatomy of alert rule</h3>\n<pre><code>groups:\n- name: example\n  rules:\n  - alert: InstanceDown\n    expr: up == 0\n    for: 5m  # wait 5m before firing - avoid flaps\n    labels:\n      severity: critical\n      team: infra\n    annotations:\n      summary: \"Instance {{ $labels.instance }} down\"\n      description: \"{{ $labels.instance }} of job {{ $labels.job }} has been down for >5m\"\n      runbook_url: \"https://wiki/runbook/instance-down\"\n</code></pre>\n\n<h3>Good vs Bad Alerts</h3>\n<pre><code># BAD - noisy, no for\n- alert: HighCPU\n  expr: node_cpu_usage > 80\n\n# GOOD - specific, waits, ratio\n- alert: HighCPU\n  expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100) > 85\n  for: 15m\n  labels:\n    severity: warning\n  annotations:\n    summary: \"High CPU on {{ $labels.instance }}\"\n\n# BAD - disk 90% but temp spike during backup\nnode_filesystem_free_bytes / node_filesystem_size_bytes < 0.1\n\n# GOOD - predict full in 4h\n- alert: DiskWillFill\n  expr: predict_linear(node_filesystem_free_bytes{mountpoint=\"/\"}[1h], 4*3600) < 0\n  for: 30m\n\n# BAD - error rate on low traffic\nrate(http_requests_total{status=~\"5..\"}[5m]) > 1\n\n# GOOD - error ratio + enough traffic\n  expr: |\n    sum by(job) (rate(http_requests_total{status=~\"5..\"}[5m]))\n    /\n    sum by(job) (rate(http_requests_total[5m])) > 0.05\n    and\n    sum by(job) (rate(http_requests_total[5m])) > 10\n</code></pre>\n\n<h3>FOR is your friend</h3>\n<p><code>for: 5m</code> means alert must be true continuously 5 min. Filters temporary blips like deployment restarts.</p>\n\n<div class=\"lab\"><strong>🧪 Lab 6:</strong> Write 5 alerts, trigger them, show for clause prevents flapping.</div>\n"
  },
  {
    "id": "ch11",
    "title": "Alertmanager: Security Guard Control Room",
    "analogy": "Control room decides who to call, when to silence, when grouping makes sense",
    "emoji": "🛡️",
    "desc": "Routing, grouping, inhibition, silences, receivers - Slack, Email, PagerDuty.",
    "content": "\n<h2>🛡️ Alertmanager = Human Firewall Between Alert Rules and Your Sleep</h2>\n\n<p>Prometheus fires alerts -> Alertmanager deduplicates, groups, routes, silences, then sends.</p>\n\n<pre><code>                Prometheus Rules\n                      |\n              +-------v--------+\n              |  Alertmanager  |\n              |  group_by: [alertname, cluster]\n              |  group_wait: 30s\n              |  group_interval: 5m\n              |  repeat_interval: 4h\n              +--+------+------+--+\n                 |      |      |\n              Slack  Email PagerDuty\n</code></pre>\n\n<h3>alertmanager.yml</h3>\n<pre><code>global:\n  slack_api_url: 'https://hooks.slack.com/...'\nroute:\n  group_by: ['alertname','cluster','service']\n  group_wait: 30s\n  group_interval: 5m\n  repeat_interval: 4h\n  receiver: 'slack-team'\n  routes:\n    - match:\n        severity: critical\n      receiver: pagerduty\n      continue: true\n    - match:\n        team: backend\n      receiver: slack-backend\n\nreceivers:\n  - name: slack-team\n    slack_configs:\n      - channel: '#alerts'\n        title: '{{ .GroupLabels.alertname }}'\n        text: '{{ range .Alerts }}{{ .Annotations.description }}{{ end }}'\n  - name: pagerduty\n    pagerduty_configs:\n      - service_key: 'your-key'\n\ninhibit_rules:\n  - source_match:\n      severity: 'critical'\n    target_match:\n      severity: 'warning'\n    equal: ['instance','alertname']  # If critical down, suppress warning on same instance\n\n# prometheus.yml\nalerting:\n  alertmanagers:\n    - static_configs:\n        - targets: ['alertmanager:9093']\n</code></pre>\n\n<h3>Grouping - Don't spam 100 alerts</h3>\n<p>If 10 instances down same job, group into ONE slack message, not 10.</p>\n\n<h3>Silences - Maintenance mode</h3>\n<p>UI -> New Silence -> matcher: job=\"api\" -> 2h. Like telling guard \"Ignore building A, we're fixing wiring.\"</p>\n\n<h3>Lab 7 - Route to Slack</h3>\n<pre><code>docker run -d -p 9093:9093 -v $(pwd)/alertmanager.yml:/etc/alertmanager/alertmanager.yml prom/alertmanager\n\n# Test\ncurl -XPOST http://localhost:9093/api/v1/alerts -d '[{\n  \"labels\":{\"alertname\":\"Test\",\"severity\":\"warning\"},\n  \"annotations\":{\"summary\":\"Test alert\"},\n  \"startsAt\":\"2024-01-01T00:00:00Z\"\n}]'\n</code></pre>\n"
  },
  {
    "id": "ch12",
    "title": "HA, Federation & Remote Write",
    "analogy": "Multiple power plants + one national grid view",
    "emoji": "🌐",
    "desc": "High availability pairs, federation for global view, long-term storage with Thanos/Cortex/Mimir.",
    "content": "\n<h2>🌐 One Prometheus Can't See Whole Country</h2>\n\n<h3>Problem 1: Single point of failure</h3>\n<p>Run 2 identical Prometheus collecting same targets. Both fire alerts, Alertmanager deduplicates.</p>\n<pre><code># prometheus1.yml and prometheus2.yml identical\n# Both scrape same jobs\n# Both send to same Alertmanager cluster\n# Alertmanager uses --cluster flag to dedup\ndocker run prom/alertmanager --cluster.peer=alertmanager2:9093\n</code></pre>\n\n<h3>Federation - Global view</h3>\n<pre><code># Global Prometheus scrapes from datacenter Proms\nscrape_configs:\n  - job_name: 'federate'\n    honor_labels: true\n    metrics_path: '/federate'\n    params:\n      'match[]':\n        - '{job=\"prometheus\"}'\n        - '{__name__=~\"job:.*\"}'  # only aggregated recording rules\n    static_configs:\n      - targets: ['prometheus-dc1:9090','prometheus-dc2:9090']\n</code></pre>\n\n<p>Analogy: Each city power plant reports summarized usage to national grid, not every house meter.</p>\n\n<h3>Remote Write - Long term storage</h3>\n<pre><code># prometheus.yml -> send to Thanos/Mimir/Cortex\nremote_write:\n  - url: \"http://thanos-receive:19291/api/v1/receive\"\n    queue_config:\n      capacity: 5000\n\nremote_read:\n  - url: \"http://thanos-query:10902/api/v1/read\"\n</code></pre>\n\n<h3>Long-term options</h3>\n<ul>\n<li><b>Thanos:</b> adds global query + unlimited retention on S3</li>\n<li><b>Cortex/Mimir:</b> horizontally scalable Prometheus</li>\n<li><b>VictoriaMetrics:</b> drop-in, efficient</li>\n</ul>\n\n<div class=\"lab\"><strong>🧪 Lab 9:</strong> Set up two Prometheuses, federate a global one, query global.</div>\n"
  },
  {
    "id": "ch13",
    "title": "Pushgateway & Short-Lived Jobs",
    "analogy": "Construction site temporary meter that reports once",
    "emoji": "⏱️",
    "desc": "When to use (and NOT use) Pushgateway, cron jobs, batch jobs.",
    "content": "\n<h2>⏱️ Not All Jobs Wait for Meter Reader</h2>\n<p>Prometheus pulls. But a cron job runs 30 seconds at 2AM. Reader may miss it. Solution: job pushes to intermediate box.</p>\n\n<pre><code>            Cron Job (2AM, 30s)\n                |\n                | push metrics\n                v\n          Pushgateway :9091  <-- Prometheus scrapes pushgateway every 15s\n                ^\n                |\n          Prometheus\n</code></pre>\n\n<h3>Run Pushgateway</h3>\n<pre><code>docker run -d -p 9091:9091 prom/pushgateway\n\n# prometheus.yml\n- job_name: pushgateway\n  static_configs:\n    - targets: ['pushgateway:9091']\n  honor_labels: true  # keep job/instance from pushed metrics\n</code></pre>\n\n<h3>Push from job - Bash</h3>\n<pre><code># Bad example - but shows pattern\necho \"batch_job_last_run $(date +%s)\" | curl --data-binary @- http://pushgateway:9091/metrics/job/backup/instance/server1\n\n# Backup script\ncat <<EOF | curl --data-binary @- http://pushgateway:9091/metrics/job/backup\n# TYPE backup_duration_seconds gauge\nbackup_duration_seconds 45.3\n# TYPE backup_last_success gauge\nbackup_last_success $(date +%s)\n# TYPE backup_files_total counter\nbackup_files_total 1234\nEOF\n</code></pre>\n\n<h3>Python</h3>\n<pre><code>from prometheus_client import CollectorRegistry, Gauge, push_to_gateway\nregistry = CollectorRegistry()\ng = Gauge('job_last_success_unixtime','Last success', registry=registry)\ng.set_to_current_time()\npush_to_gateway('pushgateway:9091', job='nightly_etl', registry=registry)\n</code></pre>\n\n<div class=\"analogy\"><strong>⚠️ WARNING:</strong> Pushgateway is NOT for long-running services. It keeps last pushed value forever - stale metrics trap! Use only for batch/cron. For services, expose /metrics and let Prometheus pull.</div>\n\n<h3>When NOT to use Pushgateway</h3>\n<p>You're building a web service that runs always -> expose /metrics endpoint, don't push.</p>\n"
  },
  {
    "id": "ch14",
    "title": "Production Hardening: Meter Box Locks",
    "analogy": "Locking meter box, limiting who can read it, preventing overload",
    "emoji": "🔒",
    "desc": "Security, relabeling, cardinality explosion, TLS, auth, limits.",
    "content": "\n<h2>🔒 The 3 Reasons Prometheus Dies in Prod</h2>\n<p>1. Cardinality explosion (metrics with user_id label = millions series) <br>\n2. No auth (anyone can see your metrics) <br>\n3. TSDB disk full</p>\n\n<h3>Cardinality - The Killer</h3>\n<pre><code># DEADLY - 1M users * 100 endpoints = 100M series -> OOM\nhttp_requests_total{user_id=\"123\", path=\"/api\"}  # NEVER!\n\n# OK - bounded labels\nhttp_requests_total{status=\"200\", method=\"GET\", endpoint=\"/api/users\"} # ~ 50 values\n\n# Fix in relabel: drop high-cardinality label\nmetric_relabel_configs:\n  - source_labels: [__name__]\n    regex: 'http_requests_total'\n    action: keep\n  - regex: 'user_id'\n    action: labeldrop\n\n# Limit\n--storage.tsdb.retention.size=50GB\nsample_limit: 5000  # per scrape\n</code></pre>\n\n<h3>TLS & Basic Auth</h3>\n<pre><code># prometheus.yml supports TLS\nscrape_configs:\n  - job_name: secure-app\n    scheme: https\n    tls_config:\n      ca_file: /certs/ca.crt\n      cert_file: /certs/client.crt\n      key_file: /certs/client.key\n    basic_auth:\n      username: prom\n      password: s3cret\n\n# Protect Prometheus itself with reverse proxy (nginx + basic auth)\n# Or use --web.config.file with tls + auth\nweb:\n  tls_server_config:\n    cert_file: /certs/server.crt\n    key_file: /certs/server.key\n  basic_auth_users:\n    admin: $2y$10$...bcrypt...\n</code></pre>\n\n<h3>Retention & WAL</h3>\n<pre><code>prometheus --storage.tsdb.path=/data \\\n  --storage.tsdb.retention.time=30d \\\n  --storage.tsdb.retention.size=100GB \\\n  --storage.tsdb.min-block-duration=30m \\\n  --storage.tsdb.max-block-duration=30m\n</code></pre>\n\n<h3>Best Practices Checklist</h3>\n<pre><code>[x] No high-cardinality labels (user_id, email, request_id)\n[x] Use recording rules for expensive queries\n[x] Alert on Prometheus itself: PrometheusDown, TSDB storage\n[x] Monitor scrape duration & samples\n  - alert: PrometheusScrapeTooSlow\n    expr: scrape_duration_seconds > 10\n[x] Backup rules & SD files in Git\n</code></pre>\n"
  },
  {
    "id": "ch15",
    "title": "Capstone: Production Monitoring Stack",
    "analogy": "Build full smart building with meters everywhere + security HQ + dashboard",
    "emoji": "🏆",
    "desc": "End-to-end microservices monitoring, SLOs, Grafana, runbook.",
    "content": "\n<h2>🏆 Capstone: You Are Ready to Sell This</h2>\n\n<p>Build monitoring for 3-service app: frontend, api, postgres. Deliver SLO dashboards & on-call playbook.</p>\n\n<h3>Architecture Goal</h3>\n<pre><code>[frontend:3000/metrics] ->|\n[api:8080/metrics]       ->|-> Prometheus (15s) -> Recording Rules -> Alerts -> Alertmanager -> Slack\n[postgres_exporter:9187] ->|     |\n                            -> Grafana (Dashboard: RED + USE + SLO)\n[blackbox:9115 probe frontend]\n</code></pre>\n\n<h3>Docker Compose for Capstone</h3>\n<pre><code>version: '3'\nservices:\n  prometheus:\n    image: prom/prometheus\n    ports: [\"9090:9090\"]\n    volumes: [\"./prometheus.yml:/etc/prometheus/prometheus.yml\",\"./rules.yml:/etc/prometheus/rules.yml\"]\n  node-exporter:\n    image: prom/node-exporter\n    ports: [\"9100:9100\"]\n  alertmanager:\n    image: prom/alertmanager\n    ports: [\"9093:9093\"]\n    volumes: [\"./alertmanager.yml:/etc/alertmanager/alertmanager.yml\"]\n  blackbox:\n    image: prom/blackbox-exporter\n    ports: [\"9115:9115\"]\n  grafana:\n    image: grafana/grafana\n    ports: [\"3000:3000\"]\n    environment: [GF_SECURITY_ADMIN_PASSWORD=admin]\n  api:\n    build: ./demo-api  # your app exposing /metrics\n    ports: [\"8080:8080\"]\n</code></pre>\n\n<h3>Rules for Capstone</h3>\n<pre><code>groups:\n- name: slo\n  rules:\n  - record: job:request:rate5m\n    expr: sum by(job) (rate(http_requests_total[5m]))\n  - alert: HighErrorRate\n    expr: |\n      sum by(job) (rate(http_requests_total{status=~\"5..\"}[5m]))\n      / sum by(job) (rate(http_requests_total[5m])) > 0.05\n    for: 5m\n    labels: {severity: critical}\n    annotations: {summary: \"{{$labels.job}} error rate >5%\"}\n  - alert: SlowAPI\n    expr: histogram_quantile(0.95, sum by(le) (rate(http_duration_seconds_bucket[5m]))) > 0.5\n    for: 10m\n    labels: {severity: warning}\n</code></pre>\n\n<h3>Deliverables Checklist</h3>\n<ul>\n<li>✅ Prometheus scraping 5+ targets</li>\n<li>✅ 4 recording rules (rate, error_ratio, p95, availability)</li>\n<li>✅ 3 alerting rules (down, error rate, latency) with <code>for</code></li>\n<li>✅ Alertmanager routing critical to PagerDuty mock + Slack</li>\n<li>✅ Grafana dashboard linked (show Prometheus as datasource)</li>\n<li>✅ Runbook: what to do when HighErrorRate fires (3 steps)</li>\n<li>✅ Screenshot of Targets page all green + one alert firing</li>\n</ul>\n\n<h3>What Next?</h3>\n<p>Grafana Blueprint next: visual layer. Thanos/Mimir for long term. OpenTelemetry for traces. You now know meters, calculator, guard. You can monitor anything.</p>\n\n<div class=\"lab\"><strong>Final Challenge:</strong> Delete one exporter, see <code>up==0</code> alert fire, silence it for 1h, fix it, check alert resolves. That's real SRE workflow!</div>\n"
  }
];
